Using TensorFlow backend.
WARNING:tensorflow:From /c1/apps/anaconda/4.3.1/lib/python3.5/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
train_model imported
load_model imported
get_rank_info imported
predict_cosine_similarity imported
Word2Vec imported
WordNetLemmatizer imported
get_similar_words imported
nltk imported
prepare_data imported
sent_tokenize imported
stopwords imported
word_tokenize imported
Traceback (most recent call last):
  File "./main.py", line 153, in <module>
    idx = int(f.read())
ValueError: invalid literal for int() with base 10: ''
